# Generated by Django 5.0.4 on 2024-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linewebhook',
            name='reply_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
